//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_HDPHONGLAB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETPHIEUNHAP
    {
        public int MAPN { get; set; }
        public string MAHC { get; set; }
        public string MATB { get; set; }
        public string MADC { get; set; }
        public Nullable<int> SOLUONGNHAP { get; set; }
        public Nullable<double> GIANHAP { get; set; }
        public Nullable<double> THANHTIEN { get; set; }
    
        public virtual DUNGCU DUNGCU { get; set; }
        public virtual HOACHAT HOACHAT { get; set; }
        public virtual PHIEUNHAP PHIEUNHAP { get; set; }
        public virtual THIETBI THIETBI { get; set; }
    }
}
