//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_HDPHONGLAB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETPHIEUXUAT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CHITIETPHIEUXUAT()
        {
            this.XUATHOACHATs = new HashSet<XUATHOACHAT>();
        }
    
        public int MACTPX { get; set; }
        public string MAHC { get; set; }
        public string MATB { get; set; }
        public string MADC { get; set; }
        public Nullable<System.DateTime> NGAYXUAT { get; set; }
    
        public virtual DUNGCU DUNGCU { get; set; }
        public virtual HOACHAT HOACHAT { get; set; }
        public virtual THIETBI THIETBI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<XUATHOACHAT> XUATHOACHATs { get; set; }
    }
}
