//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_HDPHONGLAB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_DUNGCU
    {
        public string MADC { get; set; }
        public Nullable<int> SOLO { get; set; }
        public string XUATXU { get; set; }
        public string DONVI { get; set; }
        public Nullable<int> SOPHIEUNHAP { get; set; }
    
        public virtual DUNGCU DUNGCU { get; set; }
    }
}
