//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_HDPHONGLAB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOIMATKHAU
    {
        public int MAND { get; set; }
        public string EMAIL { get; set; }
        public string PASSWORD { get; set; }
        public string NEWPASSWORD { get; set; }
        public string CONFIRMPASSWORD { get; set; }
    
        public virtual NGUOIDUNG NGUOIDUNG { get; set; }
    }
}
