//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_HDPHONGLAB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOACHAT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HOACHAT()
        {
            this.CHITIETPHIEUNHAPs = new HashSet<CHITIETPHIEUNHAP>();
            this.CHITIETPHIEUXUATs = new HashSet<CHITIETPHIEUXUAT>();
            this.PHIEUTRAs = new HashSet<PHIEUTRA>();
        }
    
        public string MAHC { get; set; }
        public string TENHC { get; set; }
        public Nullable<int> MALHC { get; set; }
        public Nullable<int> THONGSO { get; set; }
        public string CASNO { get; set; }
        public string DONVI { get; set; }
        public Nullable<int> LUONGNHAP { get; set; }
        public Nullable<int> LUONGXUAT { get; set; }
        public Nullable<int> LUONGTON { get; set; }
        public Nullable<int> LUONGTHANHLY { get; set; }
        public Nullable<double> GIANHAP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETPHIEUNHAP> CHITIETPHIEUNHAPs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETPHIEUXUAT> CHITIETPHIEUXUATs { get; set; }
        public virtual CT_HOACHAT CT_HOACHAT { get; set; }
        public virtual DUTRUHOACHAT DUTRUHOACHAT { get; set; }
        public virtual LOAIHOACHAT LOAIHOACHAT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHIEUTRA> PHIEUTRAs { get; set; }
    }
}
