//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_HDPHONGLAB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NGUOIDUNG
    {
        public int MAND { get; set; }
        public string USERNAME { get; set; }
        public string PASSWORD { get; set; }
        public string CONFIRMPASSWORD { get; set; }
        public string HOTEN { get; set; }
        public string EMAIL { get; set; }
        public string DIENTHOAI { get; set; }
        public string DIACHI { get; set; }
        public Nullable<int> MAQUYEN { get; set; }
    
        public virtual DOIMATKHAU DOIMATKHAU { get; set; }
        public virtual PHANQUYEN PHANQUYEN { get; set; }
    }
}
