//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_HDPHONGLAB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUXUATPHONGLAB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PHIEUXUATPHONGLAB()
        {
            this.SINHVIENs = new HashSet<SINHVIEN>();
        }
    
        public int MAPXPHLAB { get; set; }
        public Nullable<System.DateTime> THOIGIANXUAT { get; set; }
        public string NOIDUNG { get; set; }
        public string NGUOIXUAT { get; set; }
        public string MAPHLAB { get; set; }
        public Nullable<bool> CHAPNHAN { get; set; }
        public string NGUOICHAPNHAN { get; set; }
        public string GHICHU { get; set; }
    
        public virtual PHONGLAB PHONGLAB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SINHVIEN> SINHVIENs { get; set; }
    }
}
