//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_HDPHONGLAB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUXUAT
    {
        public int MAPX { get; set; }
        public Nullable<int> THOIGIANXUAT { get; set; }
        public string NOIDUNG { get; set; }
        public Nullable<System.DateTime> NGAYXUAT { get; set; }
        public string MAPHBAN { get; set; }
        public Nullable<bool> CHAPNHAN { get; set; }
        public string NGUOICHAPNHAN { get; set; }
        public string TU { get; set; }
        public string DEN { get; set; }
        public string GHICHU { get; set; }
    
        public virtual PHONGBAN PHONGBAN { get; set; }
    }
}
