//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_HDPHONGLAB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUTRA
    {
        public int MAPT { get; set; }
        public System.DateTime NGAYTRA { get; set; }
        public string NOIDUNG { get; set; }
        public string MAHC { get; set; }
        public string NGUOITRA { get; set; }
        public string MAPHLAB { get; set; }
        public int? SLTRA { get; set; }
        public string TU { get; set; }
        public string DEN { get; set; }
        public string GHICHU { get; set; }
    
        public virtual HOACHAT HOACHAT { get; set; }
        public virtual PHONGLAB PHONGLAB { get; set; }
    }
}
