//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_HDPHONGLAB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUNHAP
    {
        public int MAPN { get; set; }
        public Nullable<System.DateTime> NGAYNHAP { get; set; }
        public string NOIDUNG { get; set; }
        public string MANCC { get; set; }
        public string NGUOINHAN { get; set; }
        public string MAPHLAB { get; set; }
        public string TU { get; set; }
        public string DEN { get; set; }
        public Nullable<double> TONGTIEN { get; set; }
        public string GHICHU { get; set; }
    
        public virtual CHITIETPHIEUNHAP CHITIETPHIEUNHAP { get; set; }
        public virtual NCC NCC { get; set; }
        public virtual PHONGLAB PHONGLAB { get; set; }
    }
}
