//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_HDPHONGLAB.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QL_HDPHONGLABEntities : DbContext
    {
        public QL_HDPHONGLABEntities()
            : base("name=QL_HDPHONGLABEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CHITIETPHIEUNHAP> CHITIETPHIEUNHAPs { get; set; }
        public virtual DbSet<CHITIETPHIEUXUAT> CHITIETPHIEUXUATs { get; set; }
        public virtual DbSet<CT_DUNGCU> CT_DUNGCU { get; set; }
        public virtual DbSet<CT_HOACHAT> CT_HOACHAT { get; set; }
        public virtual DbSet<CT_THIETBI> CT_THIETBI { get; set; }
        public virtual DbSet<DOIMATKHAU> DOIMATKHAUs { get; set; }
        public virtual DbSet<DUNGCU> DUNGCUs { get; set; }
        public virtual DbSet<DUTRUDUNGCU> DUTRUDUNGCUs { get; set; }
        public virtual DbSet<DUTRUHOACHAT> DUTRUHOACHATs { get; set; }
        public virtual DbSet<DUTRUTHIETBI> DUTRUTHIETBIs { get; set; }
        public virtual DbSet<GIANGVIEN> GIANGVIENs { get; set; }
        public virtual DbSet<HOACHAT> HOACHATs { get; set; }
        public virtual DbSet<LOAIHOACHAT> LOAIHOACHATs { get; set; }
        public virtual DbSet<NCC> NCCs { get; set; }
        public virtual DbSet<NGUOIDUNG> NGUOIDUNGs { get; set; }
        public virtual DbSet<NSX> NSXes { get; set; }
        public virtual DbSet<PHANQUYEN> PHANQUYENs { get; set; }
        public virtual DbSet<PHIEUNHAP> PHIEUNHAPs { get; set; }
        public virtual DbSet<PHIEUTRA> PHIEUTRAs { get; set; }
        public virtual DbSet<PHIEUXUAT> PHIEUXUATs { get; set; }
        public virtual DbSet<PHIEUXUATPHONGLAB> PHIEUXUATPHONGLABs { get; set; }
        public virtual DbSet<PHONGBAN> PHONGBANs { get; set; }
        public virtual DbSet<PHONGLAB> PHONGLABs { get; set; }
        public virtual DbSet<SINHVIEN> SINHVIENs { get; set; }
        public virtual DbSet<SUKIEN> SUKIENs { get; set; }
        public virtual DbSet<THIETBI> THIETBIs { get; set; }
        public virtual DbSet<XUATHOACHAT> XUATHOACHATs { get; set; }
    }
}
