//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_HDPHONGLAB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUKIEN
    {
        public int MASK { get; set; }
        public string MAPHLAB { get; set; }
        public string MAGV { get; set; }
        public Nullable<System.DateTime> BD { get; set; }
        public Nullable<System.DateTime> KT { get; set; }
        public string ThemeColor { get; set; }
        public string MOTA { get; set; }
    
        public virtual GIANGVIEN GIANGVIEN { get; set; }
        public virtual PHONGLAB PHONGLAB { get; set; }
    }
}
