//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_HDPHONGLAB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class XUATHOACHAT
    {
        public int MACTPX { get; set; }
        public string MAHC_id { get; set; }
        public Nullable<int> SOLUONGXUAT { get; set; }
    
        public virtual CHITIETPHIEUXUAT CHITIETPHIEUXUAT { get; set; }
    }
}
